name: example
description: A project that showcases usage of flutter_cache_manager
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  baseflow_plugin_template: ^2.1.2
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_cache_manager:
    path: ../
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
