name: flutter_cache_manager_firebase
description: CacheManager implementation for firebase_storage. Uses the gs:// as key and translates to https://
version: 2.1.3
homepage: https://github.com/Baseflow/flutter_cache_manager

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.2
  firebase_storage: '>=12.0.0 <14.0.0'
  path_provider: ^2.1.6
  path: ^1.9.1
  retry: ^3.1.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
